# Generated by Django 4.2.2 on 2023-06-13 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barang',
            old_name='description',
            new_name='merk',
        ),
    ]
