# Generated by Django 4.2.2 on 2023-06-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjualan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penjualan',
            name='tendered_amount',
            field=models.FloatField(default=0),
        ),
    ]
